List<String> facts = [
  "Mars is the fourth planet from the Sun.",
  "Olympus Mons is the tallest volcano in the solar system.",
  "Mars has the largest canyon, Valles Marineris.",
  "A Martian year lasts 687 Earth days.",
  "A day on Mars is 24 hours 37 minutes.",
  "Mars is about half the size of Earth.",
  "Mars has two moons: Phobos and Deimos.",
  "Mars' gravity is 38% of Earth's gravity.",
  "Mars appears red due to iron oxide dust.",
  "Mars has giant planet-wide dust storms.",
  "Mars has ice caps made of water and CO₂.",
  "Sunsets on Mars appear blue.",
  "Mars has seasons like Earth due to its tilt.",
  "Average surface temperature on Mars is -63°C.",
  "Mars may have underground liquid water today.",
  "Mars' atmosphere is mostly carbon dioxide.",
  "Atmosphere on Mars is very thin.",
  "Mars has no global magnetic field.",
  "Robots have explored Mars for decades.",
  "NASA’s Curiosity rover landed in 2012.",
  "Mars once had flowing rivers and lakes.",
  "Evidence of ancient microbial life is being studied.",
  "Mars has recurring slope lineae (possible water streaks).",
  "Martian dust is very fine and pervasive.",
  "Mars has auroras, but not like Earth’s.",
  "Mars has frequent meteorite impacts.",
  "Some Martian meteorites have landed on Earth.",
  "Mars' temperature swings drastically day to night.",
  "Phobos will crash into Mars one day.",
  "Mars’ sky appears pink during the day.",
  "The Sun looks smaller from Mars than Earth.",
  "NASA’s Ingenuity helicopter flew on Mars in 2021.",
  "Mars missions include rovers, orbiters, and landers.",
  "Mars’ thin atmosphere can't block harmful radiation.",
  "Wind on Mars shapes dunes and dust devils.",
  "Mars is a target for future human missions.",
  "Mars’ surface pressure is less than 1% of Earth’s.",
  "Mars has cliffs, craters, plains, and volcanoes.",
  "Valles Marineris stretches over 4,000 km long.",
  "Curiosity found organic molecules in Martian soil.",
  "Mars can be seen from Earth without a telescope.",
  "Mars has seasons that last twice as long as Earth’s.",
  "Mars’ core may be liquid, but not well understood.",
  "Martian moons may be captured asteroids.",
  "Perseverance rover landed in Jezero Crater in 2021.",
  "Mars' orbit is more elliptical than Earth's.",
  "Mars was named after the Roman god of war.",
  "Mars' average distance from Earth is 225 million km.",
  "Many spacecraft have failed trying to reach Mars.",
  "Terraforming Mars is a popular science fiction topic.",
];
