/// A constant map that provides a mapping between widget parameter names and mcd values
const Map<String, String> parameterMap = {
  't': 'Temperature',
  'p': 'Pressure',
  'rho': 'Density',
  'u': 'W-E wind component',
  'v': 'S-N wind component',
  'wind': 'Horizontal wind speed',
  'zradius': 'Radial distance from planet center',
  'zareoid': 'Altitude above areoid',
  'zsurface': 'Altitude above local surface',
  'oroheight': 'Orographic height',
  'oro_gcm': 'GCM orography',
  'theta_s': 'Local slope inclination',
  'psi_s': 'Local slope orientation',
  'marsau': 'Sun-Mars distance',
  'ls': 'Ls, solar longitude of Mars',
  'loctime': 'LST: Local true solar time',
  'lmeantime': 'LMT: Local mean time at sought longitude',
  'utime': 'Universal solar time',
  'solzenang': 'Solar zenith angle',
  'tsurf': 'Surface temperature',
  'ps': 'Surface pressure',
  'ps_gcm': 'GCM surface pressure',
  'potential_temp': 'Potential temperature',
  'w_l': 'Downward vertical wind component',
  'zonal_slope_wind': 'Zonal slope wind component',
  'merid_slope_wind': 'Meridional slope wind component',
  'rmsps': 'Surface pressure RMS day to day variations',
  'rmstsurf': 'Surface temperature RMS day to day variations',
  'altrmsp': 'Atmospheric pressure RMS day to day variations',
  'rmsrho': 'Density RMS day to day variations',
  'rmst': 'Temperature RMS day to day variations',
  'rmsu': 'Zonal wind RMS day to day variations',
  'rmsv': 'Meridional wind RMS day to day variations',
  'rmsw': 'Vertical wind RMS day to day variations',
  'fluxtop_dn_sw': 'Incident solar flux at top of the atmosphere',
  'fluxtop_up_sw': 'Solar flux reflected to space',
  'fluxsurf_dn_sw': 'Incident solar flux on horizontal surface',
  'fluxsurf_dn_sw_hr': 'Incident solar flux on local slope',
  'fluxsurf_up_sw': 'Reflected solar flux on horizontal surface',
  'fluxtop_lw': 'Thermal IR flux to space',
  'fluxsurf_lw': 'Thermal IR flux on surface',
  'z_0': 'GCM surface roughness length z0',
  'thermal_inertia': 'GCM surface thermal inertia',
  'ground_albedo': 'GCM surface bare ground albedo',
  'dod': 'Monthly mean dust column visible optical depth',
  'tauref': 'Daily mean dust column visible optical depth',
  'dust_mmr': 'Dust mass mixing ratio',
  'dust_reff': 'Dust effective radius',
  'dust_dep': 'Daily mean dust deposition rate',
  'co2ice': 'Monthly mean surface CO2 ice layer',
  'surf_h2o_ice': 'Monthly mean surface H2O layer',
  'water_cap': 'GCM perennial surface water ice',
  'col_h2ovapor': 'Water vapor column',
  'vmr_h2o': 'Water vapor vol. mixing ratio',
  'col_h2oice': 'Water ice column',
  'vmr_h2oice': 'Water ice mixing ratio',
  'h2oice_reff': 'Water ice effective radius',
  'zmax': 'Convective Planetary Boundary Layer height',
  'wstar_up': 'Max. upward convective wind within the PBL',
  'wstar_dn': 'Max. downward convective wind within the PBL',
  'vvv': 'Convective vertical wind variance at level z',
  'vhf': 'Convective eddy vertical heat flux at level z',
  'surfstress': 'Surface wind stress',
  'sensib_flux': 'Surface sensible heat flux',
  'Cp': 'Air heat capacity Cp',
  'gamma': 'Ratio of specific heats Cp/Cv',
  'Rgas': 'Molecular gas constant R',
  'viscosity': 'Air viscosity estimation',
  'pscaleheight': 'Scale height H(p)',
  'vmr_co2': '[CO2] volume mixing ratio',
  'vmr_n2': '[N2] volume mixing ratio',
  'vmr_ar': '[Ar] volume mixing ratio',
  'vmr_co': '[CO] volume mixing ratio',
  'vmr_o': '[O] volume mixing ratio',
  'vmr_o2': '[O2] volume mixing ratio',
  'vmr_o3': '[O3] volume mixing ratio',
  'vmr_h': '[H] volume mixing ratio',
  'vmr_h2': '[H2] volume mixing ratio',
  'vmr_he': '[He] volume mixing ratio',
  'col_co2': 'CO2 column',
  'col_n2': 'N2 column',
  'col_ar': 'Ar column',
  'col_co': 'CO column',
  'col_o': 'O column',
  'col_o2': 'O2 column',
  'col_o3': 'O3 column',
  'col_h': 'H column',
  'col_h2': 'H2 column',
  'col_he': 'He column',
  'vmr_elec': 'Electron number density',
  'col_elec': 'Total electronic content (TEC)',
};
